services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile.manuel
    image: demo-manuel:latest
    container_name: demo-manuel
    ports:
      - "8081:8080"
    restart: unless-stopped
