name: Build

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: docker run -u "$(id -u):$(id -g)" -v "$PWD:/app" -w /app gradle:8.14-jdk21 gradle build
