name: Documentation

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pandoc:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run pandoc
        run: |
          docker run --rm --volume "${{ github.workspace }}:/data" --user $(id -u):$(id -g) \
            pandoc/extra metadata.yml README.md --lua-filter=remove-badges.lua \
            --template eisvogel -o doc-${{ github.ref_name }}.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: doc-${{ github.ref_name }}.pdf