name: Build, test and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Docker Compose
        run: docker compose build

      - name: Start container with Docker Compose
        run: docker compose up -d

      - name: Clean old Docker images
        if: always()
        run: docker image prune -f
