name: Manuel's pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Docker Compose
        run: docker compose -f docker-compose.manuel.yml build

      - name: Start container with Docker Compose
        run: docker compose -f docker-compose.manuel.yml up -d

      - name: Clean old Docker images
        if: always()
        run: docker image prune -f
